DROP DATABASE IF EXISTS atticus_backend_challenge;
CREATE DATABASE atticus_backend_challenge;
\c atticus_backend_challenge;

drop table if exists songs cascade;
create type genre_type as enum ('Rock', 'Pop', 'Rap', 'R&B');
create table if not exists songs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) not null,
  genre genre_type not null,
  artist varchar(255) not null,
  length int not null,
  file_path varchar(2056) not null,
  ranking int
)

insert into "songs" (name, genre, artist, length, file_path) values ('heather', 'Pop', 'conan_gray', 198, 'healther_file_path');

insert into "songs" (name, genre, artist, length, file_path, ranking) values ('nangtho', 'R&B', 'hoang_dung', 200, 'nangtho_file_path', 3);

